module.exports = {
  users: [
    {
      uid: 0,
      name: "Darin Loh Han Sum",
      username: "darinlohsexy",
      password: "darintoosexy",
      email: "darindamnsexy@sexymail.com",
      hoots: 3,
      answers: 4,
      stickers: 6,
      rank: "noob",
    },
    {
      uid: 1,
      name: "Tan Chin Kiat",
      username: "chinkiatsexy",
      password: "chinsexy",
      email: "chindamnsexy@sexymail.com",
      hoots: 4,
      answers: 2,
      stickers: 1,
      rank: "novice",
    },
    {
      uid: 2,
      name: "Thumb Jin Lin",
      username: "jinlinsexy",
      password: "jinlintoosexy",
      email: "jinlindamnsexy@sexymail.com",
      hoots: 1,
      answers: 1,
      stickers: 7,
      rank: "ultra",
    },
    {
      uid: 3,
      name: "Andy Lamb",
      username: "andysexy",
      password: "andytoosexy",
      email: "andydamnsexy@sexymail.com",
      hoots: 1,
      answers: 1,
      stickers: 7,
      rank: "expert",
    },
  ],
  hoots: [
    {
      hid: 0,
      uid: 2,
      name: "jinlinsexy",
      content: "What should i do about this?",
    },
    {
      hid: 1,
      uid: 0,
      name: "darinlohsexy",
      content: "Why am I so handsome?",
    },
    {
      hid: 2,
      uid: 2,
      name: "jinlinsexy",
      content: "I might be too smart?",
    },
    {
      hid: 3,
      uid: 3,
      name: "andysexy",
      content: "I like pigs, what should I do?",
    },
    {
      hid: 4,
      uid: 0,
      name: "darinlohsexy",
      content: "I am kinda hungry, what should I eat?",
    },
  ],
  replies: [
    {
      rid: 0,
      hid: 2,
      uid: 2,
      name: "jinlinsexy",
      content: "You should get a girlfriend!",
    },
    {
      rid: 1,
      hid: 1,
      uid: 3,
      name: "andysexy",
      content: "Good to be confident!",
    },
    {
      rid: 2,
      hid: 4,
      uid: 1,
      name: "chinkiatsexy",
      content: "Get some pizza!",
    },
    {
      rid: 3,
      hid: 1,
      uid: 3,
      name: "andysexy",
      content: "I am pretty handsome too!",
    },
    {
      rid: 4,
      hid: 1,
      uid: 2,
      name: "jinlinsexy",
      content: "I agree!",
    },
  ],
};
